
class ClassfiedArgs:
    def __init__(
        self,
        console_log_level=None,
        console_log_file=None,
        console_log_simple=False,
        v2=False,
        v_parameterization=False,
        pretrained_model_name_or_path=None,
        tokenizer_cache_dir=None,
        train_data_dir=None,
        cache_info=False,
        shuffle_caption=False,
        caption_separator=',',
        caption_extension='.caption',
        caption_extention=None,
        keep_tokens=0,
        keep_tokens_separator='',
        secondary_separator=None,
        enable_wildcard=False,
        caption_prefix=None,
        caption_suffix=None,
        color_aug=False,
        flip_aug=False,
        face_crop_aug_range=None,
        random_crop=False,
        debug_dataset=False,
        resolution=None,
        cache_latents=False,
        vae_batch_size=1,
        cache_latents_to_disk=False,
        enable_bucket=False,
        min_bucket_reso=256,
        max_bucket_reso=1024,
        bucket_reso_steps=64,
        bucket_no_upscale=False,
        token_warmup_min=1,
        token_warmup_step=0,
        alpha_mask=False,
        dataset_class=None,
        caption_dropout_rate=0.0,
        caption_dropout_every_n_epochs=0,
        caption_tag_dropout_rate=0.0,
        reg_data_dir=None,
        in_json=None,
        dataset_repeats=1,
        output_dir=None,
        output_name=None,
        huggingface_repo_id=None,
        huggingface_repo_type=None,
        huggingface_path_in_repo=None,
        huggingface_token=None,
        huggingface_repo_visibility=None,
        save_state_to_huggingface=False,
        resume_from_huggingface=False,
        async_upload=False,
        save_precision='fp16',
        save_every_n_epochs=None,
        save_every_n_steps=None,
        save_n_epoch_ratio=None,
        save_last_n_epochs=None,
        save_last_n_epochs_state=None,
        save_last_n_steps=None,
        save_last_n_steps_state=None,
        save_state=False,
        save_state_on_train_end=False,
        resume=None,
        train_batch_size=1,
        max_token_length=None,
        mem_eff_attn=False,
        torch_compile=False,
        dynamo_backend='inductor',
        xformers=True,
        sdpa=False,
        vae=None,
        max_train_steps=1600,
        max_train_epochs=None,
        max_data_loader_n_workers=8,
        persistent_data_loader_workers=False,
        seed=None,
        gradient_checkpointing=False,
        gradient_accumulation_steps=1,
        mixed_precision='fp16',
        full_fp16=False,
        full_bf16=False,
        fp8_base=False,
        ddp_timeout=None,
        ddp_gradient_as_bucket_view=False,
        ddp_static_graph=False,
        clip_skip=None,
        logging_dir=None,
        log_with=None,
        log_prefix=None,
        log_tracker_name=None,
        wandb_run_name=None,
        log_tracker_config=None,
        wandb_api_key=None,
        log_config=False,
        noise_offset=None,
        noise_offset_random_strength=False,
        multires_noise_iterations=None,
        ip_noise_gamma=None,
        ip_noise_gamma_random_strength=False,
        multires_noise_discount=0.3,
        adaptive_noise_scale=None,
        zero_terminal_snr=False,
        min_timestep=None,
        max_timestep=None,
        loss_type='l2',
        huber_schedule='snr',
        huber_c=0.1,
        lowram=False,
        highvram=False,
        sample_every_n_steps=None,
        sample_at_first=False,
        sample_every_n_epochs=None,
        sample_prompts=None,
        sample_sampler='ddim',
        config_file=None,
        output_config=False,
        metadata_title=None,
        metadata_author=None,
        metadata_description=None,
        metadata_license=None,
        metadata_tags=None,
        prior_loss_weight=1.0,
        conditioning_data_dir=None,
        masked_loss=False,
        deepspeed=False,
        zero_stage=2,
        offload_optimizer_device=None,
        offload_optimizer_nvme_path=None,
        offload_param_device=None,
        offload_param_nvme_path=None,
        zero3_init_flag=False,
        zero3_save_16bit_model=False,
        fp16_master_weights_and_gradients=False,
        optimizer_type='',
        use_8bit_adam=False,
        use_lion_optimizer=False,
        learning_rate=2e-06,
        max_grad_norm=1.0,
        optimizer_args=None,
        lr_scheduler_type='',
        lr_scheduler_args=None,
        lr_scheduler='constant',
        lr_warmup_steps=0,
        lr_decay_steps=0,
        lr_scheduler_num_cycles=1,
        lr_scheduler_power=1,
        fused_backward_pass=False,
        lr_scheduler_timescale=None,
        lr_scheduler_min_lr_ratio=None,
        dataset_config=None,
        min_snr_gamma=None,
        scale_v_pred_loss_like_noise_pred=False,
        v_pred_like_loss=None,
        debiased_estimation_loss=False,
        weighted_captions=False,
        no_metadata=False,
        save_model_as='safetensors',
        unet_lr=None,
        text_encoder_lr=None,
        network_weights=None,
        network_module=None,
        network_dim=None,
        network_alpha=1,
        network_dropout=None,
        network_args=None,
        network_train_unet_only=False,
        network_train_text_encoder_only=False,
        training_comment=None,
        dim_from_weights=False,
        scale_weight_norms=None,
        base_weights=None,
        base_weights_multiplier=None,
        no_half_vae=False,
        skip_until_initial_step=False,
        initial_epoch=None,
        initial_step=None,
        cache_text_encoder_outputs=False,
        cache_text_encoder_outputs_to_disk=False,
        disable_mmap_load_safetensors=False
    ):
        self.console_log_level = console_log_level
        self.console_log_file = console_log_file
        self.console_log_simple = console_log_simple
        self.v2 = v2
        self.v_parameterization = v_parameterization
        self.pretrained_model_name_or_path = pretrained_model_name_or_path
        self.tokenizer_cache_dir = tokenizer_cache_dir
        self.train_data_dir = train_data_dir
        self.cache_info = cache_info
        self.shuffle_caption = shuffle_caption
        self.caption_separator = caption_separator
        self.caption_extension = caption_extension
        self.caption_extention = caption_extention
        self.keep_tokens = keep_tokens
        self.keep_tokens_separator = keep_tokens_separator
        self.secondary_separator = secondary_separator
        self.enable_wildcard = enable_wildcard
        self.caption_prefix = caption_prefix
        self.caption_suffix = caption_suffix
        self.color_aug = color_aug
        self.flip_aug = flip_aug
        self.face_crop_aug_range = face_crop_aug_range
        self.random_crop = random_crop
        self.debug_dataset = debug_dataset
        self.resolution = resolution
        self.cache_latents = cache_latents
        self.vae_batch_size = vae_batch_size
        self.cache_latents_to_disk = cache_latents_to_disk
        self.enable_bucket = enable_bucket
        self.min_bucket_reso = min_bucket_reso
        self.max_bucket_reso = max_bucket_reso
        self.bucket_reso_steps = bucket_reso_steps
        self.bucket_no_upscale = bucket_no_upscale
        self.token_warmup_min = token_warmup_min
        self.token_warmup_step = token_warmup_step
        self.alpha_mask = alpha_mask
        self.dataset_class = dataset_class
        self.caption_dropout_rate = caption_dropout_rate
        self.caption_dropout_every_n_epochs = caption_dropout_every_n_epochs
        self.caption_tag_dropout_rate = caption_tag_dropout_rate
        self.reg_data_dir = reg_data_dir
        self.in_json = in_json
        self.dataset_repeats = dataset_repeats
        self.output_dir = output_dir
        self.output_name = output_name
        self.huggingface_repo_id = huggingface_repo_id
        self.huggingface_repo_type = huggingface_repo_type
        self.huggingface_path_in_repo = huggingface_path_in_repo
        self.huggingface_token = huggingface_token
        self.huggingface_repo_visibility = huggingface_repo_visibility
        self.save_state_to_huggingface = save_state_to_huggingface
        self.resume_from_huggingface = resume_from_huggingface
        self.async_upload = async_upload
        self.save_precision = save_precision
        self.save_every_n_epochs = save_every_n_epochs
        self.save_every_n_steps = save_every_n_steps
        self.save_n_epoch_ratio = save_n_epoch_ratio
        self.save_last_n_epochs = save_last_n_epochs
        self.save_last_n_epochs_state = save_last_n_epochs_state
        self.save_last_n_steps = save_last_n_steps
        self.save_last_n_steps_state = save_last_n_steps_state
        self.save_state = save_state
        self.save_state_on_train_end = save_state_on_train_end
        self.resume = resume
        self.train_batch_size = train_batch_size
        self.max_token_length = max_token_length
        self.mem_eff_attn = mem_eff_attn
        self.torch_compile = torch_compile
        self.dynamo_backend = dynamo_backend
        self.xformers = xformers
        self.sdpa = sdpa
        self.vae = vae
        self.max_train_steps = max_train_steps
        self.max_train_epochs = max_train_epochs
        self.max_data_loader_n_workers = max_data_loader_n_workers
        self.persistent_data_loader_workers = persistent_data_loader_workers
        self.seed = seed
        self.gradient_checkpointing = gradient_checkpointing
        self.gradient_accumulation_steps = gradient_accumulation_steps
        self.mixed_precision = mixed_precision
        self.full_fp16 = full_fp16
        self.full_bf16 = full_bf16
        self.fp8_base = fp8_base
        self.ddp_timeout = ddp_timeout
        self.ddp_gradient_as_bucket_view = ddp_gradient_as_bucket_view
        self.ddp_static_graph = ddp_static_graph
        self.clip_skip = clip_skip
        self.logging_dir = logging_dir
        self.log_with = log_with
        self.log_prefix = log_prefix
        self.log_tracker_name = log_tracker_name
        self.wandb_run_name = wandb_run_name
        self.log_tracker_config = log_tracker_config
        self.wandb_api_key = wandb_api_key
        self.log_config = log_config
        self.noise_offset = noise_offset
        self.noise_offset_random_strength = noise_offset_random_strength
        self.multires_noise_iterations = multires_noise_iterations
        self.ip_noise_gamma = ip_noise_gamma
        self.ip_noise_gamma_random_strength = ip_noise_gamma_random_strength
        self.multires_noise_discount = multires_noise_discount
        self.adaptive_noise_scale = adaptive_noise_scale
        self.zero_terminal_snr = zero_terminal_snr
        self.min_timestep = min_timestep
        self.max_timestep = max_timestep
        self.loss_type = loss_type
        self.huber_schedule = huber_schedule
        self.huber_c = huber_c
        self.lowram = lowram
        self.highvram = highvram
        self.sample_every_n_steps = sample_every_n_steps
        self.sample_at_first = sample_at_first
        self.sample_every_n_epochs = sample_every_n_epochs
        self.sample_prompts = sample_prompts
        self.sample_sampler = sample_sampler
        self.config_file = config_file
        self.output_config = output_config
        self.metadata_title = metadata_title
        self.metadata_author = metadata_author
        self.metadata_description = metadata_description
        self.metadata_license = metadata_license
        self.metadata_tags = metadata_tags
        self.prior_loss_weight = prior_loss_weight
        self.conditioning_data_dir = conditioning_data_dir
        self.masked_loss = masked_loss
        self.deepspeed = deepspeed
        self.zero_stage = zero_stage
        self.offload_optimizer_device = offload_optimizer_device
        self.offload_optimizer_nvme_path = offload_optimizer_nvme_path
        self.offload_param_device = offload_param_device
        self.offload_param_nvme_path = offload_param_nvme_path
        self.zero3_init_flag = zero3_init_flag
        self.zero3_save_16bit_model = zero3_save_16bit_model
        self.fp16_master_weights_and_gradients = fp16_master_weights_and_gradients
        self.optimizer_type = optimizer_type
        self.use_8bit_adam = use_8bit_adam
        self.use_lion_optimizer = use_lion_optimizer
        self.learning_rate = learning_rate
        self.max_grad_norm = max_grad_norm
        self.optimizer_args = optimizer_args
        self.lr_scheduler_type = lr_scheduler_type
        self.lr_scheduler_args = lr_scheduler_args
        self.lr_scheduler = lr_scheduler
        self.lr_warmup_steps = lr_warmup_steps
        self.lr_decay_steps = lr_decay_steps
        self.lr_scheduler_num_cycles = lr_scheduler_num_cycles
        self.lr_scheduler_power = lr_scheduler_power
        self.fused_backward_pass = fused_backward_pass
        self.lr_scheduler_timescale = lr_scheduler_timescale
        self.lr_scheduler_min_lr_ratio = lr_scheduler_min_lr_ratio
        self.dataset_config = dataset_config
        self.min_snr_gamma = min_snr_gamma
        self.scale_v_pred_loss_like_noise_pred = scale_v_pred_loss_like_noise_pred
        self.v_pred_like_loss = v_pred_like_loss
        self.debiased_estimation_loss = debiased_estimation_loss
        self.weighted_captions = weighted_captions
        self.no_metadata = no_metadata
        self.save_model_as = save_model_as
        self.unet_lr = unet_lr
        self.text_encoder_lr = text_encoder_lr
        self.network_weights = network_weights
        self.network_module = network_module
        self.network_dim = network_dim
        self.network_alpha = network_alpha
        self.network_dropout = network_dropout
        self.network_args = network_args
        self.network_train_unet_only = network_train_unet_only
        self.network_train_text_encoder_only = network_train_text_encoder_only
        self.training_comment = training_comment
        self.dim_from_weights = dim_from_weights
        self.scale_weight_norms = scale_weight_norms
        self.base_weights = base_weights
        self.base_weights_multiplier = base_weights_multiplier
        self.no_half_vae = no_half_vae
        self.skip_until_initial_step = skip_until_initial_step
        self.initial_epoch = initial_epoch
        self.initial_step = initial_step
        self.cache_text_encoder_outputs = cache_text_encoder_outputs
        self.cache_text_encoder_outputs_to_disk = cache_text_encoder_outputs_to_disk
        self.disable_mmap_load_safetensors = disable_mmap_load_safetensors
